### ISSUE TITLE
Change command handlers (and other enhancements)

### ISSUE THREAD

**Issue by WindowsVistaisCool** [DerpTaterTot/axolotlbot#4]
I was looking through this code, and I noticed you were using `discord.ext` instead of normal `discord.Client()`, but you have this `@bot.event` and `async def on_message` for commands, which is just a waste of the EXT libs. For DM channels, you don't need to create a dm first, but just send to the `user` object. You also don't have to strip a message (I think):
```py
if message.content.lower() == "axolotl bot is bad": #triggers on the message "axolotl bot is bad"
        await message.author.send("buff axolotl is coming for you, so prepare yourself mortal.\nYou shall not stand the wrath of BUFF AXOLOTL")
        await message.author.send(file=discord.File('buffaxolotl.png'))
```
I do see you have a level system, and I advise using a database, instead of a single, long, json file.
For your `.level` command, I advice turning that command into a `@bot.command()` object, where you can also control permissions, and cooldown (with discord `BucketType`). This new command type uses a `context` object, which is different to a message object. To fix this issue, I just made `message = ctx.message`. I did also notice that your prefix was `$`, but you have conflicting prefixes, so I just called this function using your native prefix. If you want to change the prefix for the whole bot, but not your other existing commands, just change it during `bot` initialization. You will have to redeclare all variables however, or just global existing ones. I'm also importing `datetime`, which does timestamps for embed with `datetime.datetime.utcnow()`. You don't need this, but I have found it very helpful. Here is my proposed code:
```py
from datetime import datetime

...

@bot.command(aliases=['lvl', 'level'])
async def level(ctx): #runs when .level or .lvl is sent
    message = ctx.message #declares message as a ctx.message object
    spam = bot.get_channel(768876717422936115)
    if message.channel == spam: #only sends in spam and commands
        level = "level: " + str(levels[str(message.author.id)]["level"]) + "\n" #accesses the level of the person who sent it from the json file.   
        msgs = "xp: " + str(levels[str(message.author.id)]["xp"]) + "/" + str(100 * (levels[str(message.author.id)]["level"] - 1) + 50) #accesses the xp needed from the json file, (current xp/needed xp)
        
        levelinfoembed = discord.Embed(title = level + msgs, color = 0xff85a2, timestamp=datetime.utcnow()) #creates embed of levels (and sets a timestamp)
        levelinfoembed.set_footer(text='Retrieved Data')

        await message.channel.send(embed = levelinfoembed) #you could also use await ctx.send(embed=levelinfoembed)
```
However, this code will not run until it is allowed to, which is activated from the `on_message` function:
```py
@bot.event
async def on_message(message):
    ...
    await client.proccess_commands(message)
```
I think that's all I have to suggest for now, but if I miss anything, I will put it in the comments of this issue.

**Comment by DerpTaterTot** [comment]
Could you show how I could use a database? I have never used one before so ¯\_(ツ)_/¯

**Comment by DerpTaterTot** [comment]
I've implemented the rest of your code, and it works well, thanks! (We've been struggling on how to use bot commands for a while now)

**Comment by WindowsVistaisCool** [comment]
no problem! (i've been using dpy for like 7 months now)
the database, i'm not sure, i'll dig into it tonight, because I dont have a level system :l

**Comment by Epicmania** [comment]
I totally understand what you guys are talking about.

**Comment by WindowsVistaisCool** [comment]
I'm going to close this issue, and if I have any more ideas, I'll open a new issue.
